config/routes.rb
XpendNet::Application.routes.draw do
  get "subscriptions/unsubscribe"

  delete "subscriptions/destroy"

  get "archive", :to => 'archive#index'

  get "archive/:date", :to => 'archive#month', :as => :archive_month

  get "archive/:date/:outlay_category_id", :to => 'archive#category', :as => :archive_category

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  root :to => 'outlays#index'
  resources :outlay_records, :controller => :outlays do
    get :earlier, :on => :collection
  end
  resources :outlay_categories
  resources :house_books

end

app/views/shared/_notification_area.html.erb
<%
  a = alert
  n = notice
%>

<% if a || n %>
  <div class="outer_block small_height_block">
    <% if n %>
      <p class="notice"><%= n %><em>V</em></p>
    <% end %>
    <% if a %>
      <p class="alert"><%= a %><em>V</em></p>
    <% end %>
    
  </div>
<% end %>

app/views/shared/_top_nav.html.erb
<div class="top_nav_wrapper">
  <div class="top_nav">
    <% if user_signed_in? %>
      <p class="app_nav">
        <%= link_to t('common.main'), root_path, :id => "logo" %> |
        <!--<%= link_to t('common.books'), house_books_path %> | -->
        <%= link_to t('common.categories'), outlay_categories_path %> |
        <%= link_to t('common.trends') %> |
        <%= link_to t('common.archive'), archive_path %>
      </p>
    <% else %>
      <p class="app_nav">
        xpend.net | <%= t 'intro' %>
      </p>
    <% end %>
    <p class="user_nav">
    <% unless user_signed_in? %>
      <%= link_to t('common.register'), new_user_registration_path %> |
      <%= link_to t('common.sign_in'), new_user_session_path %>
    <% else %>
      <%= t 'common.logged_in_as' %> <%= link_to current_user.email, edit_user_registration_path %>. <%= t 'common.not_you' %>
      <%= link_to t('common.logout'), destroy_user_session_path %>
    <% end %>
    </p>
  </div>
</div>