config/routes.rb
XpendNet::Application.routes.draw do
  get "subscriptions/unsubscribe"

  delete "subscriptions/destroy"

  get "archive", :to => 'archive#index'

  get "archive/:date", :to => 'archive#month', :as => :archive_month

  get "archive/:date/:outlay_category_id", :to => 'archive#category', :as => :archive_category

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  root :to => 'outlays#index'
  resources :outlay_records, :controller => :outlays do
    get :earlier, :on => :collection
  end
  resources :outlay_categories
  resources :house_books

end

app/models/house_book.rb
class HouseBook < ActiveRecord::Base
  has_many :outlay_records
  has_many :outlay_categories
end

app/controllers/house_books_controller.rb
class HouseBooksController < ApplicationController
  # GET /house_books
  # GET /house_books.xml
  def index
    @house_books = HouseBook.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @house_books }
    end
  end

  # GET /house_books/1
  # GET /house_books/1.xml
  def show
    @house_book = HouseBook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @house_book }
    end
  end

  # GET /house_books/new
  # GET /house_books/new.xml
  def new
    @house_book = HouseBook.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @house_book }
    end
  end

  # GET /house_books/1/edit
  def edit
    @house_book = HouseBook.find(params[:id])
  end

  # POST /house_books
  # POST /house_books.xml
  def create
    @house_book = HouseBook.new(params[:house_book])

    respond_to do |format|
      if @house_book.save
        format.html { redirect_to(@house_book, :notice => 'House book was successfully created.') }
        format.xml  { render :xml => @house_book, :status => :created, :location => @house_book }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @house_book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /house_books/1
  # PUT /house_books/1.xml
  def update
    @house_book = HouseBook.find(params[:id])

    respond_to do |format|
      if @house_book.update_attributes(params[:house_book])
        format.html { redirect_to(@house_book, :notice => 'House book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @house_book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /house_books/1
  # DELETE /house_books/1.xml
  def destroy
    @house_book = HouseBook.find(params[:id])
    @house_book.destroy

    respond_to do |format|
      format.html { redirect_to(house_books_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/house_books_helper.rb
module HouseBooksHelper
end

app/views/house_books/_form.html.erb
<%= form_for(@house_book) do |f| %>
  <% if @house_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_book.errors.count, "error") %> prohibited this house_book from being saved:</h2>

      <ul>
      <% @house_book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/house_books/edit.html.erb
<h1>Editing house book</h1>

<%= render 'form' %>

<%= link_to 'Show', @house_book %> |
<%= link_to 'Back', house_books_path %>

app/views/house_books/index.html.erb
<h1>House books</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @house_books.each do |house_book| %>
  <tr>
    <td><%= house_book.name %></td>
    <td><%= link_to 'Show', house_book %></td>
    <td><%= link_to 'Edit', edit_house_book_path(house_book) %></td>
    <td><%= link_to 'Destroy', house_book, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New house book', new_house_book_path %>

app/views/house_books/new.html.erb
<h1>New house_book</h1>

<%= render 'form' %>

<%= link_to 'Back', house_books_path %>

app/views/house_books/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_house_book_path(@house_book) %> |
<%= link_to 'Back', house_books_path %>