config/routes.rb
XpendNet::Application.routes.draw do
  get "subscriptions/unsubscribe"

  delete "subscriptions/destroy"

  get "archive", :to => 'archive#index'

  get "archive/:date", :to => 'archive#month', :as => :archive_month

  get "archive/:date/:outlay_category_id", :to => 'archive#category', :as => :archive_category

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  root :to => 'outlays#index'
  resources :outlay_records, :controller => :outlays do
    get :earlier, :on => :collection
  end
  resources :outlay_categories
  resources :house_books

end

app/models/outlay_category.rb
class OutlayCategory < ActiveRecord::Base
  has_many :outlay_records
  validates_presence_of :name
end

app/controllers/outlay_categories_controller.rb
class OutlayCategoriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :define_house_book

  # GET /outlay_categories
  # GET /outlay_categories.xml
  def index
    @outlay_categories = @house_book.outlay_categories

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @outlay_categories }
    end
  end

  # GET /outlay_categories/1
  # GET /outlay_categories/1.xml
  def show
    @outlay_category = @house_book.outlay_categories.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @outlay_category }
    end
  end

  # GET /outlay_categories/new
  # GET /outlay_categories/new.xml
  def new
    @outlay_category = @house_book.outlay_categories.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @outlay_category }
    end
  end

  # GET /outlay_categories/1/edit
  def edit
    @outlay_category = @house_book.outlay_categories.find(params[:id])
  end

  # POST /outlay_categories
  # POST /outlay_categories.xml
  def create
    @outlay_category = @house_book.outlay_categories.new(params[:outlay_category])

    respond_to do |format|
      if @outlay_category.save
        format.html { redirect_to(@outlay_category, :notice => 'Outlay category was successfully created.') }
        format.xml  { render :xml => @outlay_category, :status => :created, :location => @outlay_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @outlay_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /outlay_categories/1
  # PUT /outlay_categories/1.xml
  def update
    @outlay_category = @house_book.outlay_categories.find(params[:id])

    respond_to do |format|
      if @outlay_category.update_attributes(params[:outlay_category])
        format.html { redirect_to(@outlay_category, :notice => 'Outlay category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @outlay_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /outlay_categories/1
  # DELETE /outlay_categories/1.xml
  def destroy
    @outlay_category = @house_book.outlay_categories.find(params[:id])
    @outlay_category.destroy

    respond_to do |format|
      format.html { redirect_to(outlay_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/outlay_categories_helper.rb
module OutlayCategoriesHelper
end

app/views/outlay_categories/_form.html.erb
<%= form_for(@outlay_category) do |f| %>
  <% if @outlay_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= t 'errors.template.header.other', :count =>@outlay_category.errors.count %>:</h2>

      <ul>
      <% @outlay_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <div class="actions">
    <%= f.submit t("common.submit") %>
  </div>
<% end %>

app/views/outlay_categories/edit.html.erb
<h1><%= t 'outlay_category.edit' %></h1>

<%= render 'form' %>

<%= link_to t('outlay_category.show'), @outlay_category %> |
<%= link_to t('common.back'), outlay_categories_path %>

app/views/outlay_categories/index.html.erb
<h1><%= t 'outlay_category.list' %></h1>

<table>
  <tr>
    <th><%= t 'outlay_category.name' %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outlay_categories.each do |outlay_category| %>
  <tr>
    <td><%= outlay_category.name %></td>
    <td><%= link_to t('common.show'), outlay_category %></td>
    <td><%= link_to t('common.edit'), edit_outlay_category_path(outlay_category) %></td>
    <td><%= link_to t('common.destroy'), outlay_category, :confirm => t ('outlay_category.destroy_confirm'), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('outlay_category.new'), new_outlay_category_path %>
<%= link_to t('common.back'), root_path %>

app/views/outlay_categories/new.html.erb
<h1><%= t 'outlay_category.new' %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), outlay_categories_path %>

app/views/outlay_categories/show.html.erb
<p>
<%= @outlay_category.name %>
</p>

<%= link_to t('outlay_category.edit'), edit_outlay_category_path(@outlay_category) %> |
<%= link_to t ('common.back'), outlay_categories_path %>