config/routes.rb
XpendNet::Application.routes.draw do
  get "subscriptions/unsubscribe"

  delete "subscriptions/destroy"

  get "archive", :to => 'archive#index'

  get "archive/:date", :to => 'archive#month', :as => :archive_month

  get "archive/:date/:outlay_category_id", :to => 'archive#category', :as => :archive_category

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  root :to => 'outlays#index'
  resources :outlay_records, :controller => :outlays do
    get :earlier, :on => :collection
  end
  resources :outlay_categories
  resources :house_books

end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  before_filter :authenticate_user!
  before_filter :define_house_book

  def index
    @months = @house_book.outlay_records.find :all,
      :select => "min(created_at) as created_at, SUM(amount) as amount",
      # :conditions => "date_part('year', created_at) = 2010",
      :group => "date_part('month', created_at)",
      :order => 'created_at DESC'
    @categories = monthly_categories(@months.first.created_at)
  end

  def month
    @categories = monthly_categories(params[:date].to_date)
  end

  def category
    date = params[:date].to_date
    @outlays = @house_book.outlay_records.find :all,
      :conditions => [
        "outlay_category_id = ? AND created_at BETWEEN ? AND ?",
        params[:outlay_category_id],
        date.beginning_of_month,
        date.end_of_month
      ],
      :include => :outlay_category
  end

  private

  def monthly_categories(date)
    @house_book.outlay_records.find :all,
      :select => "outlay_category_id, SUM(amount) as amount, MIN(created_at) as created_at",
      :conditions => ["created_at BETWEEN ? AND ?", date.beginning_of_month, date.end_of_month],
      :group => "outlay_category_id",
      :include => :outlay_category
  end
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/views/archive/_categories.html.erb
<% 
  sum_amount = categories.collect(&:amount).sum
  max_amount = categories.collect(&:amount).max
%>
<% for category in categories do %>
  <div class="category_wrap" data-date="<%= category.created_at.to_date %>">
    <div class="category" style="padding: 3px; padding-left: 0;">
      <%= link_to category.outlay_category.name, archive_category_path(:date => category.created_at.to_date, :outlay_category_id => category.outlay_category_id), :remote => true %>
      <span class="amount">
        <%= category.amount %><br/>
      </span>
    </div>
    <div style="background: #d0d0da; height: 15px; line-height: 15px; font-size: 10px; border-top: 15px solid #dfdfdf;margin: 5px; margin-left: 0; font-weight: 700; color: gray; text-shadow: 1px 1px 1px #fff; width: <%= [(70 * category.amount / max_amount).to_i, 7].max %>%">
      <%= (100 * category.amount / sum_amount).to_i %>%
    </div>
    <div class="outlays" data-category="<%= category.outlay_category.id %>">
    </div>
  </div>

<% end %>

app/views/archive/_outlays.html.erb
<% for record in @outlays do %>
  <div class="record" data-id="<%= record.id %>">
    <%= record.note %>&nbsp;
    
    <span class="amount">
      <%= record.amount %>
    </span>
  </div>
<% end %>

app/views/archive/category.js.erb
$('.category_wrap[data-date=<%= params[:date].to_date %>] .outlays[data-category=<%= params[:outlay_category_id] %>]').html('<%= escape_javascript(render :partial => 'outlays') %>');

app/views/archive/index.html.erb
<h1><%= t 'archive.title' %></h1>
<div class="archive">
  <div class="archive_months">
    <% @months.each_with_index do |month, i| %>
      <div class="month<%= i == 0 ? ' active' : '' %>" data-date="<%= month.created_at.to_date %>">
        <%= link_to month.created_at.strftime("%B '%y"), archive_month_path(:date => month.created_at.to_date), :remote => true %><br/>
        <span class="small">
          <%= month.amount.to_i %>
        </span>
      </div>
    <% end %>
  </div>
  <div id="categories" class="monthly_expend outlays" style="width: 369px">
    <%= render :partial => 'categories', :locals => { :categories => @categories } %>
  </div>
</div>

app/views/archive/month.js.erb
$('#categories').html('<%= escape_javascript(render :partial => 'categories', :locals => { :categories => @categories }) %>');
$month = $('.month[data-date=<%= params[:date] %>]');
$month.parent().find('.month.active').removeClass('active');
$month.addClass('active');